# Generated by Django 3.2.25 on 2024-06-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240620_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('disease', models.CharField(max_length=200, verbose_name='疾患')),
                ('team', models.CharField(choices=[('A', 'チームA'), ('B', 'チームB'), ('C', 'チームC')], max_length=1, verbose_name='チーム')),
                ('doctor', models.CharField(max_length=100, verbose_name='Dr')),
                ('pt', models.CharField(max_length=100, verbose_name='PT')),
                ('pt_upper', models.IntegerField(verbose_name='PT（上限）')),
                ('pt_lower', models.IntegerField(verbose_name='PT（下限）')),
                ('ot_upper', models.IntegerField(verbose_name='OT（上限）')),
                ('ot_lower', models.IntegerField(verbose_name='OT（下限）')),
                ('st_upper', models.IntegerField(verbose_name='ST（上限）')),
                ('st_lower', models.IntegerField(verbose_name='ST（下限）')),
                ('document_manager', models.CharField(max_length=100, verbose_name='書類責任者')),
                ('max_days', models.IntegerField(verbose_name='上限日数')),
                ('admission_date', models.DateField(verbose_name='入院日')),
                ('admission_fim_m', models.IntegerField(verbose_name='入院時FIM-m')),
                ('admission_fim_c', models.IntegerField(verbose_name='入院時FIM-c')),
                ('total_fim', models.IntegerField(verbose_name='合計FIM')),
                ('hospitalization_days', models.IntegerField(verbose_name='入院日数')),
                ('predicted_fim_m', models.IntegerField(verbose_name='予測FIM-m')),
                ('outcome', models.CharField(max_length=200, verbose_name='アウトカム（退院目標）')),
                ('recovery_period_limit', models.DateField(verbose_name='回復期期限')),
                ('days_until_limit', models.IntegerField(verbose_name='回復期期限までの日数')),
                ('planned_discharge_date', models.DateField(verbose_name='予定退院日')),
                ('planned_transfer', models.CharField(choices=[('home', '自宅'), ('facility', '施設'), ('hospital', '病院'), ('other', 'その他')], max_length=20, verbose_name='予定転帰先')),
                ('exclusion_request', models.BooleanField(default=False, verbose_name='除外希望')),
                ('exclusion_reason', models.TextField(blank=True, null=True, verbose_name='除外理由')),
                ('exclusion_decision', models.BooleanField(default=False, verbose_name='除外判定')),
                ('not_applicable', models.BooleanField(default=False, verbose_name='対象外')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='退院日')),
                ('discharge_fim_m', models.IntegerField(blank=True, null=True, verbose_name='退院時FIM-m')),
                ('discharge_fim_c', models.IntegerField(blank=True, null=True, verbose_name='退院時FIM-c')),
                ('actual_transfer', models.CharField(blank=True, choices=[('home', '自宅'), ('facility', '施設'), ('hospital', '病院'), ('other', 'その他')], max_length=20, null=True, verbose_name='転帰先')),
                ('discharge_year', models.IntegerField(blank=True, null=True, verbose_name='退院（年）')),
                ('discharge_month', models.IntegerField(blank=True, null=True, verbose_name='退院（月）')),
                ('discharge_day', models.IntegerField(blank=True, null=True, verbose_name='退院（日）')),
                ('predicted_fim_difference', models.FloatField(blank=True, null=True, verbose_name='予測FIMの差')),
                ('predicted_fim_processing', models.FloatField(blank=True, null=True, verbose_name='予測FIMの処理列')),
                ('predicted_performance_index', models.FloatField(blank=True, null=True, verbose_name='予測実績指数')),
                ('fim_difference', models.FloatField(blank=True, null=True, verbose_name='FIMの差')),
                ('performance_index_processing', models.FloatField(blank=True, null=True, verbose_name='実績指数処理列')),
                ('performance_index', models.FloatField(blank=True, null=True, verbose_name='実績指数')),
            ],
        ),
    ]
